package com.example.myapplication

object SignRepository {
    val signs = arrayListOf<Sign>(
        Sign(1,
            "Овен",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_30.jpg",
            "21.03 – 20.04"),
        Sign(2,
            "Телец",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_35.jpg",
            "21.04 – 20.05"),
        Sign(3,
            "Близнецы",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_25.jpg",
            "21.05 – 20.06"),
        Sign(4,
            "Рак",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_31.jpg",
            "21.06 – 22.07"),
        Sign(5,
            "Лев",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_29.jpg",
            "23.07 – 22.08"),
        Sign(6,
            "Дева",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_36.jpg",
            "23.08 – 22.09"),
        Sign(7,
            "Весы",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_26.jpg",
            "23.09 – 22.10"),
        Sign(8,
            "Скорпион",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_33.jpg",
            "23.10 – 21.11"),
        Sign(9,
            "Стрелец",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_34.jpg",
            "22.11 – 21.12"),
        Sign(10,
            "Козерог",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_28.jpg",
            "22.12 – 19.01"),
        Sign(11,
            "Водолей",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_27.jpg",
            "20.01 – 18.02"),
        Sign(12,
            "Рыбы",
            "https://www.kartinki24.ru/uploads/gallery/comthumb/279/kartinki24_ru_signs_of_the_zodiac_32.jpg",
            "19.02 – 20.03"),

    )
}